file:
  # 保存文件目录
  upload-path: D:/upload/
server:
  port: 9003
spring:
#  数据库配置
  datasource:
    username: root
    url: jdbc:mysql://154.36.154.211:9002/webprint?useUnicode=true&characterEncoding=utf-8&useSSL=false&timezone=Asia/Shanghai
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  data:
#    redis配置
    redis:
      host: 103.244.88.91
      port: 6379
      password: inspur123
      timeout: 5000ms
